# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Create .env
      run: |
        echo API_KEY=${{ secrets.API_KEY }} >> .env
        echo API_KEY=${{ secrets.BOT_TOKEN }} >> .env
        echo API_KEY=${{ secrets.DATABASE_URL }} >> .env
        
    - name: Run Service
      run: |
        sudo systemctl restart stockbot.service

